/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package dev.kentrino.ktor.app

import io.kotest.core.spec.style.FunSpec
import kotlin.test.assertEquals

class MessageUtilsTest: FunSpec({
    test("testGetMessage") {
        assertEquals("Hello      World!", MessageUtils.getMessage())
    }
})
