/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
    application
}

dependencies {
    kotlinBom()
    kotlinStdlibJdk()
    coroutine()
    ktor()
    jackson()
    logging()
    implementation("org.apache.commons:commons-text:1.9")
    implementation(project(":utilities"))
    testImplementation("com.github.kentrino:json-assert:68689320bc")
    kotest()
}

application {
    // Define the main class for the application.
    mainClass.set("dev.kentrino.ktor.app.AppKt")
}
