/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.kentrino.ktor.app

import io.ktor.server.cio.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun main() {
    embeddedServer(
            factory = Netty,
            host = "0.0.0.0",
            port = 3000,
            configure = {
                callGroupSize = 200
            },
            module =  {
                this.configure()
            }
    ).applyGracefulShutdown(enable = true).start()
}
